debugClicks: true #to be deleted at the end of testing, set to true to get messages about what you clicked and where
roomDisplay:
  enabled: true
  intervalTicks: 10   # 10 ticks = 0.5s
  clearWhenOutside: true

rooms:
  terminal:
    title: "Terminal"
    world: "OSCityWorld"
    min: { x: 169, y: 85, z: 296 }
    max: { x: 194, y: 90, z: 321 }
    npcPosition: { x: 184, y: 86, z: 309 }

  learnerMode:
    title: "Learner Mode"
    world: "OSCityWorld"
    min: { x: 195, y: 86, z: 296 }
    max: { x: 204, y: 90, z: 307 }
    npcPosition: { x: 199, y: 86, z: 304 }
  
  adventurerMode:
    title: "Adventurer Mode"
    world: "OSCityWorld"
    min: { x: 195, y: 86, z: 311 }
    max: { x: 204, y: 90, z: 321 }
    npcPosition: { x: 199, y: 86, z: 318 }
  
  permissionChamber:
    title: "Permission Chamber"
    world: "OSCityWorld"
    min: { x: 82, y: -32, z: 20 }
    max: { x: 90, y: -28, z: 30 }
    npcPosition: { x: 83, y: -32, z: 21 }

  pageDirectory:
    title: "Page Table Library - Page Directory"
    world: "OSCityWorld"
    min: { x: 82, y: 18, z: 5 }
    max: { x: 90, y: 21, z: 13 }
    npcPosition: { x: 83, y: 18, z: 7 }

  pageTable1:
    title: "Page Table Library - Page Table 1"
    world: "OSCityWorld"
    min: { x: 82, y: 23, z: 5 }
    max: { x: 90, y: 26, z: 13 }
    npcPosition: { x: 89, y: 23, z: 12 }
    
  pageTable2:
    title: "Page Table Library - Page Table 2"
    world: "OSCityWorld"
    min: { x: 82, y: 28, z: 5 }
    max: { x: 90, y: 31, z: 13 }
    npcPosition: { x: 89, y: 28, z: 12 }

  pageTable3:
    title: "Page Table Library - Page Table 3"
    world: "OSCityWorld"
    min: { x: 82, y: 33, z: 5 }
    max: { x: 90, y: 36, z: 13 }
    npcPosition: { x: 89, y: 33, z: 12 }
  
  swapDistrict:
    title: "Swap District"
    world: "OSCityWorld"
    min: { x: 0, y: -34, z: 36 }
    max: { x: 43, y: -25, z: 79 }
    npcPosition: { x: 27, y: -33, z: 58 }

  ramRoom1:
    title: "RAM Room"
    world: "OSCityWorld"
    min: { x: 22, y: -60, z: 115 }
    max: { x: 34, y: -56, z: 128 }
    npcPosition: { x: 24, y: -60, z: 125 }

  ramRoom2:
    title: "RAM Room"
    world: "OSCityWorld"
    min: { x: 23, y: -60, z: 139 }
    max: { x: 36, y: -56, z: 152 }
    npcPosition: { x: 25, y: -60, z: 150 }
  
  diskRoom:
    title: "Disk Room"
    world: "OSCityWorld"
    min: { x: 23, y: -60, z: 173 }
    max: { x: 36, y: -56, z: 186 }
    npcPosition: { x: 25, y: -60, z: 184 }
  
  calculatorRoom:
    title: "Calculator Room"
    world: "OSCityWorld"
    min: { x: 25, y: -60, z: 204 }
    max: { x: 35, y: -56, z: 214 }
    npcPosition: { x: 27, y: -60, z: 212 }

  pageFaultCorridor:
    title: "Page Fault Corridor"
    world: "OSCityWorld"
    min: { x: 79, y: -34, z: 32 }
    max: { x: 93, y: -28, z: 77 }
    npcPosition: { x: 86, y: -34, z: 42 }

  lazyAllocationRoom:
    title: "Lazy Allocation Room"
    world: "OSCityWorld"
    min: { x: 95, y: -34, z: 54 }
    max: { x: 108, y: -30, z: 60 }
    npcPosition: { x: 104, y: -34, z: 58 }
  
  lazyLoadingRoom:
    title: "Lazy Loading Room"
    world: "OSCityWorld"
    min: { x: 95, y: -34, z: 70 }
    max: { x: 108, y: -30, z: 76 }
    npcPosition: { x: 104, y: -34, z: 74 }

  cowRoom:
    title: "COW Room"
    world: "OSCityWorld"
    min: { x: 95, y: -34, z: 38 }
    max: { x: 108, y: -30, z: 44 }
    npcPosition: { x: 104, y: -34, z: 42 }
  
  tlbRoom1:
    title: "TLB Room"
    world: "OSCityWorld"
    min: { x: 65, y: 17, z: -11 }
    max: { x: 81, y: 25, z: 29 }
    npcPosition: { x: 86, y: 18, z: 25 }

  tlbRoom2:
    title: "TLB Room"
    world: "OSCityWorld"
    min: { x: 91, y: 17, z: -11 }
    max: { x: 107, y: 25, z: 29 }

  tlbRoom3:
    title: "TLB Room"
    world: "OSCityWorld"
    min: { x: 81, y: 17, z: -11 }
    max: { x: 91, y: 25, z: 4 }

  tlbRoom4:
    title: "TLB Room"
    world: "OSCityWorld"
    min: { x: 81, y: 17, z: 14 }
    max: { x: 91, y: 25, z: 29 }

choiceButtons:
  # Permission chamber buttons
  btn1: # button for allowed access/lazy allocation
    world: "OSCityWorld"
    x: 90
    y: -32
    z: 22
  btn2: # button for page fault/lazy loading
    world: "OSCityWorld"
    x: 90
    y: -32
    z: 24
  btn3: # button for segmentation fault/swapping
    world: "OSCityWorld"
    x: 90
    y: -32
    z: 26
  btn4: # button for premission fault
    world: "OSCityWorld"
    x: 90
    y: -32
    z: 28
  
  # COW room buttons
  allocateCow:
    world: "OSCityWorld"
    x: 99
    y: -34
    z: 38
  terminate:
    world: "OSCityWorld"
    x: 101
    y: -34
    z: 38
  
  # Lazy allocation room buttons
  allocateLazy:
    world: "OSCityWorld"
    x: 102
    y: -34
    z: 60
  swapLazy:
    world: "OSCityWorld"
    x: 100
    y: -34
    z: 60

  cowLazyAlloc:
    world: "OSCityWorld"
    x: 100
    y: -34
    z: 54
  btnLazyAlloc: # button for "Go to RAM"/"Deny the write"
    world: "OSCityWorld"
    x: 101
    y: -34
    z: 54
  nothing:
    world: "OSCityWorld"
    x: 102
    y: -34
    z: 54
  # TLB room buttons
  hit:
    world: "OSCityWorld"
    x: 65
    y: 17
    z: 10
  miss:
    world: "OSCityWorld"
    x: 65
    y: 17
    z: 8

  # Calculator room buttons
  skipCalc:
    world: "OSCityWorld"
    x: 34
    y: -60
    z: 209
  
  continueCalc:
    world: "OSCityWorld"
    x: 30
    y: -60
    z: 213
  
  # RAM room buttons
  ramMix: # button for retry instruction/finish/continue in ram room
    world: "OSCityWorld"
    x: 26
    y: -60
    z: 127
  
  # Swap district buttons
  swapLever:
    world: "OSCityWorld"
    x: 24
    y: -33
    z: 58
  frame1btn:
    world: "OSCityWorld"
    x: 32
    y: -32
    z: 52
  frame2btn:
    world: "OSCityWorld"
    x: 32
    y: -32
    z: 66
  frame3btn:
    world: "OSCityWorld"
    x: 22
    y: -32
    z: 68
  frame4btn:
    world: "OSCityWorld"
    x: 11
    y: -32
    z: 64
  frame5btn:
    world: "OSCityWorld"
    x: 11
    y: -32
    z: 50
  frame6btn:
    world: "OSCityWorld"
    x: 24
    y: -32
    z: 47
  
tpButtons:
  learnerStart: # button to start the learner's mode, teleports to TLB room
    world: "OSCityWorld"
    destination: tlbSpawn
    message: "&aTeleported to TLB room!"
    x: 203
    y: 87
    z: 301
  
  adventurerStart: # button to start the adventurer's mode, teleports to TLB room
    world: "OSCityWorld"
    destination: tlbSpawn
    message: "&aTeleported to TLB room!"
    x: 203
    y: 87
    z: 316
  
  pt1ToChamber: # teleport to permission chamber from Page table 1
    world: "OSCityWorld"
    destination: permissionChamber
    message: "&aTeleported to Permission Chamber!"
    x: 83
    y: 23
    z: 13
  
  pt2ToChamber: # teleport to permission chamber from Page table 2
    world: "OSCityWorld"
    destination: permissionChamber
    message: "&aTeleported to Permission Chamber!"
    x: 83
    y: 28
    z: 13

  pt3ToChamber: # teleport to permission chamber from Page table 3
    world: "OSCityWorld"
    destination: permissionChamber
    message: "&aTeleported to Permission Chamber!"
    x: 83
    y: 33
    z: 13

  tlbToCalculator: # teleport to calculator room from TLB room
    world: "OSCityWorld"
    destination: calculatorRoom
    message: "&aTeleported to Calculator Room!"
    x: 107
    y: 17
    z: 9

  tlbToRam1: # teleport to ram room 1 from TLB room
    world: "OSCityWorld"
    destination: ramRoom1
    message: "&aTeleported to RAM Room!"
    x: 65
    y: 18
    z: 11
  
  per: # teleport to disk/RAM/COW room from permission chamber
    world: "OSCityWorld"
    destination: diskRoom
    message: "&aTeleported to Disk Room!"
    x: 82
    y: -32
    z: 25

  loadingToCalc: # teleport to calculator room from lazy loading room
    world: "OSCityWorld"
    destination: calculatorRoom
    message: "&aTeleported to Calculator Room!"
    x: 101
    y: -34
    z: 70
  
  loadingToDisk: # teleport to disk room from lazy loading room
    world: "OSCityWorld" 
    destination: diskRoom
    message: "&aTeleported to Disk Room!"
    x: 101
    y: -34
    z: 70

  swapToRam: # teleport to ram room from swap district
    world: "OSCityWorld"
    destination: ramRoom1
    message: "&aTeleported to RAM Room!"
    x: 22
    y: -32
    z: 58

  ramToSwap: # teleport to swap district from ram room
    world: "OSCityWorld"
    destination: swapDistrict
    message: "&aTeleported to Swap District!"
    x: 26
    y: -60
    z: 127
  
  ramToLazyAlloc: # teleport to lazy allocation room from ram room
    world: "OSCityWorld"
    destination: lazyAllocationRoom
    message: "&aTeleported to Lazy Allocation Room!"
    x: 26
    y: -60
    z: 127
  
  ramToCow: # teleport to cow room from ram room
    world: "OSCityWorld"
    destination: cowRoom
    message: "&aTeleported to COW Room!"
    x: 26
    y: -60
    z: 127
  
  diskToRam: # teleport to ram room from disk room
    world: "OSCityWorld"
    destination: ramRoom1
    message: "&aTeleported to RAM Room!"
    x: 27
    y: -60
    z: 185
  
  cowToRam: # teleport to ram room from cow room
    world: "OSCityWorld"
    destination: ramRoom1
    message: "&aTeleported to RAM Room!"
    x: 101
    y: -34
    z: 44
  
  lazyAllocToRam: # teleport to ram room from lazy allocation room
    world: "OSCityWorld"
    destination: ramRoom1
    message: "&aTeleported to RAM Room!"
    x: 101
    y: -34
    z: 54
  
  lazyAllocToCow: # teleport to cow room from lazy allocation room
    world: "OSCityWorld"
    destination: cowRoom
    message: "&aTeleported to COW Room!"
    x: 101
    y: -34
    z: 54

  
signs:
  pageTable:
    vpn1: 
      world: "OSCityWorld"
      x: 92
      y: 19
      z: 7
    vpn2: 
      world: "OSCityWorld"
      x: 92
      y: 19
      z: 9
    vpn3: 
      world: "OSCityWorld"
      x: 92
      y: 19
      z: 11
    vpn4: 
      world: "OSCityWorld"
      x: 88
      y: 19
      z: 3
    vpn5: 
      world: "OSCityWorld"
      x: 86
      y: 19
      z: 3
    vpn6: 
      world: "OSCityWorld"
      x: 84
      y: 19
      z: 3
    vpn7: 
      world: "OSCityWorld"
      x: 80
      y: 19
      z: 7
    vpn8: 
      world: "OSCityWorld"
      x: 80
      y: 19      
      z: 9
    vpn9: 
      world: "OSCityWorld"
      x: 80
      y: 19
      z: 11
  
  perChamber:
    sign1: # sign for allowed access/lazy allocation
      world: "OSCityWorld"
      x: 90
      y: -31
      z: 22
    sign2: # sign for page fault/lazy loading
      world: "OSCityWorld"
      x: 90
      y: -31
      z: 24
    sign3: # sign for segmentation fault/swapping
      world: "OSCityWorld"
      x: 90
      y: -31
      z: 26
    sign4: # sign for permission fault
      world: "OSCityWorld"
      x: 90
      y: -31
      z: 28
    sign5: # sign for "Make your decision"/"Which type of page fault is it?"
      world: "OSCityWorld"
      x: 90
      y: -30
      z: 25
  
  cow:
    toRam: 
      world: "OSCityWorld"
      x: 101
      y: -33
      z: 44
  
  lazyAllocation:
    mixSign: # sign for "Go to RAM"/"Deny the write"/"Go to COW room" in lazy allocation room
      world: "OSCityWorld"
      x: 101
      y: -33
      z: 54
    cowSign:
      world: "OSCityWorld"
      x: 100
      y: -33
      z: 54
    doNothingSign:
      world: "OSCityWorld"
      x: 102
      y: -33
      z: 54
    writeSign:
      world: "OSCityWorld"
      x: 101
      y: -32
      z: 54
  
  lazyLoading:
    mixSign: # sign for "Go to Disk"/"Go to Calculator Room" in lazy loading room
      world: "OSCityWorld"
      x: 101
      y: -33
      z: 70
  
  ramRoom:
    frame1: 
      world: "OSCityWorld"
      x: 26
      y: -59
      z: 116
    frame2: 
      world: "OSCityWorld"
      x: 28
      y: -59
      z: 116
    frame3: 
      world: "OSCityWorld"
      x: 30
      y: -59
      z: 116
    frame4: 
      world: "OSCityWorld"
      x: 32
      y: -59
      z: 116
    frame5: 
      world: "OSCityWorld"
      x: 34
      y: -59
      z: 118
    frame6: 
      world: "OSCityWorld"
      x: 34
      y: -59      
      z: 120
    frame7:
      world: "OSCityWorld"
      x: 34
      y: -59
      z: 122
    frame8:
      world: "OSCityWorld"
      x: 34
      y: -59
      z: 124 
    zeroFrame:
      world: "OSCityWorld"
      x: 32
      y: -59
      z: 127
    mixFrame:
      world: "OSCityWorld"
      x: 26
      y: -59
      z: 127

  swapDistrict:
    frame1: 
      world: "OSCityWorld"
      x: 32
      y: -32
      z: 51
    frame2: 
      world: "OSCityWorld"
      x: 32
      y: -32
      z: 65
    frame3: 
      world: "OSCityWorld"
      x: 23
      y: -32
      z: 68
    frame4: 
      world: "OSCityWorld"
      x: 11
      y: -32
      z: 65
    frame5: 
      world: "OSCityWorld"
      x: 11
      y: -32
      z: 51
    frame6: 
      world: "OSCityWorld"
      x: 23
      y: -32
      z: 47
  calculatorRoom:
    instructionsFrame1:
      world: "OSCityWorld"
      x: 25
      y: -58
      z: 208
    instructionsFrame2:
      world: "OSCityWorld"
      x: 25
      y: -58
      z: 207
    instructionsFrame3:
      world: "OSCityWorld"
      x: 25
      y: -58
      z: 206
    instructionsFrame4:
      world: "OSCityWorld"
      x: 25
      y: -59
      z: 208
    instructionsFrame5:
      world: "OSCityWorld"
      x: 25
      y: -59
      z: 207
    instructionsFrame6:
      world: "OSCityWorld"
      x: 25
      y: -59
      z: 206
    calculationFrame1:
      world: "OSCityWorld"
      x: 29
      y: -58
      z: 204
    calculationFrame2:
      world: "OSCityWorld"
      x: 30
      y: -58
      z: 204
    calculationFrame3:
      world: "OSCityWorld"
      x: 31
      y: -58
      z: 204
    calculationFrame4:
      world: "OSCityWorld"
      x: 29
      y: -59
      z: 204
    calculationFrame5:
      world: "OSCityWorld"
      x: 30
      y: -59
      z: 204
    calculationFrame6:
      world: "OSCityWorld"
      x: 31
      y: -59
      z: 204


doors:
  tlbToPt:
    world: "OSCityWorld"
    x: 86
    y: 18
    z: 14
  
  toLazyLoading:
    world: "OSCityWorld"
    x: 94
    y: -34
    z: 73

  toLazyAllocation:
    world: "OSCityWorld"
    x: 94
    y: -34
    z: 57
  
  toSwap:
    world: "OSCityWorld"
    x: 78
    y: -343
    z: 57
  toPageFaultCorridor:
    world: "OSCityWorld"
    x: 86
    y: -32
    z: 31

redstone:
  redstone1: # redstone for swap district puzzle
    world: "OSCityWorld"
    x: 32
    y: -32
    z: 50
  redstone2:
    world: "OSCityWorld"
    x: 32
    y: -32
    z: 64
  redstone3:
    world: "OSCityWorld"
    x: 24
    y: -32
    z: 68
  redstone4:
    world: "OSCityWorld"
    x: 11
    y: -32
    z: 66
  redstone5:
    world: "OSCityWorld"
    x: 11
    y: -32
    z: 52
  redstone6:
    world: "OSCityWorld"
    x: 22
    y: -32
    z: 47
    
hopper:
  world: "OSCityWorld"
  x: 30
  y: -60
  z: 205

locations:
  initialSpawn: # initial spawn point for players
    world: "OSCityWorld"
    x: 174
    y: 86
    z: 309
  
  tlbSpawn: # spawn point for TLB room
    world: "OSCityWorld"
    x: 86
    y: 17
    z: 28
  
  permissionChamber: # spawn point for permission chamber
    world: "OSCityWorld"
    x: 86
    y: -32
    z: 27

  ramRoom1: # spawn point for ram room 1
    world: "OSCityWorld"
    x: 26
    y: -60
    z: 125

  ramRoom2: # spawn point for ram room 2
    world: "OSCityWorld"
    x: 27
    y: -60
    z: 149

  diskRoom: # spawn point for disk room
    world: "OSCityWorld"
    x: 27
    y: -60
    z: 182

  calculatorRoom: # spawn point for calculator room
    world: "OSCityWorld"
    x: 33
    y: -60
    z: 212

  npc:
  name: "ยง6Kernel Guardian"
  
  welcomeMessage: |
    You have been chosen to replace me, the Kernel Guardian.
    Proceed with caution. Trust your gut, and everything will be questioned.
  
  roomGreetings:
    tlbRoom: "Welcome to the TLB Room. Here we check if your page is already cached."
    permissionChamber: "Time to check access permissions. Not all memory accesses are allowed."
    calculatorRoom: "Convert your virtual address from hexadecimal to binary here."